import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const marker = "return switch (source) {";
const bucketMarker = "const _studioMobileTextBuckets";

// A several-thousand-case expression stalls the ARM AOT compiler, including
// when inlined into callers. Keep the generated expressions intact, with small
// compiler boundaries and a constant dispatch table. First-match semantics
// matter because application branding can produce duplicate source labels.
export function splitMobileTextLookup(source: string, minimumCases = 256, chunkSize = 48) {
  if (source.includes(bucketMarker)) return source;
  const start = source.indexOf(marker);
  if (start < 0) return source;
  const fallback = source.indexOf("      _ => source,", start);
  const closing = source.indexOf("    };", fallback);
  if (fallback < 0 || closing < 0) throw new Error("Unsupported generated mobile text switch");
  const body = source.slice(start + marker.length, fallback);
  const matches = [...body.matchAll(/^      ('(?:\\.|[^'\\])*')\s*=>/gm)];
  if (matches.length < minimumCases) return source;
  const entries = matches.map((match, index) => ({
    key: match[1],
    body: body.slice(match.index, matches[index + 1]?.index ?? body.length).trimEnd(),
  }));
  const chunks = Array.from({ length: Math.ceil(entries.length / chunkSize) }, (_, index) => entries.slice(index * chunkSize, (index + 1) * chunkSize));
  const dispatch = `return switch (_studioMobileTextBuckets[source]) {\n${chunks.map((_, index) => `      ${index} => _studioMobileText${index}(l10n, source, values),`).join("\n")}\n      _ => source,\n    };`;
  const seen = new Set<string>();
  const buckets = entries.flatMap((entry, index) => {
    if (seen.has(entry.key)) return [];
    seen.add(entry.key);
    return [`  ${entry.key}: ${Math.floor(index / chunkSize)},`];
  });
  const table = `\nconst _studioMobileTextBuckets = <String, int>{\n${buckets.join("\n")}\n};\n`;
  const helpers = chunks.map((chunk, index) => `\n@pragma('vm:never-inline')\nString _studioMobileText${index}(AppLocalizations l10n, String source, Map<String, Object> values) {\n  return switch (source) {\n${chunk.map((entry) => entry.body).join("\n")}\n      _ => source,\n  };\n}\n`).join("");
  return source.slice(0, start) + dispatch + source.slice(closing + "    };".length) + table + helpers;
}

// Keep downloaded projects regeneratable with their upstream Dart tool. This
// mirrors the transformation above, without requiring Node or the studio.
export const mobileTextCompilerTool = String.raw`// Generated by OpenVTS Studio for bounded ARM AOT compilation.
String stabilizeMobileTextSource(String source) {
  const marker = 'return switch (source) {';
  if (source.contains('const _studioMobileTextBuckets')) return source;
  final start = source.indexOf(marker);
  if (start < 0) return source;
  final fallback = source.indexOf('      _ => source,', start);
  final closing = source.indexOf('    };', fallback);
  if (fallback < 0 || closing < 0) throw StateError('Unsupported generated mobile text switch');
  final body = source.substring(start + marker.length, fallback);
  final matches = RegExp(r"^      ('(?:\\.|[^'\\])*')\s*=>", multiLine: true).allMatches(body).toList();
  if (matches.length < 256) return source;
  final entries = <({String key, String body})>[];
  for (var i = 0; i < matches.length; i++) {
    entries.add((key: matches[i].group(1)!, body: body.substring(matches[i].start, i + 1 < matches.length ? matches[i + 1].start : body.length).trimRight()));
  }
  const chunkSize = 48;
  final chunkCount = (entries.length / chunkSize).ceil();
  final out = StringBuffer(source.substring(0, start))..writeln('return switch (_studioMobileTextBuckets[source]) {');
  for (var i = 0; i < chunkCount; i++) {
    out.writeln('      ' + i.toString() + ' => _studioMobileText' + i.toString() + '(l10n, source, values),');
  }
  out.writeln('      _ => source,');
  out.write('    };');
  out.write(source.substring(closing + '    };'.length));
  out.writeln('\nconst _studioMobileTextBuckets = <String, int>{');
  final seen = <String>{};
  for (var i = 0; i < entries.length; i++) {
    if (seen.add(entries[i].key)) out.writeln('  ' + entries[i].key + ': ' + (i ~/ chunkSize).toString() + ',');
  }
  out.writeln('};');
  for (var i = 0; i < chunkCount; i++) {
    out.writeln("\n@pragma('vm:never-inline')");
    out.writeln('String _studioMobileText' + i.toString() + '(AppLocalizations l10n, String source, Map<String, Object> values) {');
    out.writeln('  return switch (source) {');
    final end = (i + 1) * chunkSize < entries.length ? (i + 1) * chunkSize : entries.length;
    for (var j = i * chunkSize; j < end; j++) { out.writeln(entries[j].body); }
    out.writeln('      _ => source,');
    out.writeln('  };');
    out.writeln('}');
  }
  return out.toString();
}
`;

export async function prepareFlutterCompatibility(root: string): Promise<string[]> {
  const helperPath = path.join(/* turbopackIgnore: true */ root, "lib/shared/helpers/mobile_text.dart");
  const source = await readFile(helperPath, "utf8").catch((error: NodeJS.ErrnoException) => {
    if (error.code === "ENOENT") return undefined;
    throw error;
  });
  if (!source?.includes("Generated by tool/generate_mobile_text.dart")) return [];
  const revised = splitMobileTextLookup(source);
  if (source === revised) return [];
  const generatorPath = path.join(/* turbopackIgnore: true */ root, "tool/generate_mobile_text.dart");
  const generator = await readFile(generatorPath, "utf8");
  const writer = ".writeAsStringSync(lines.join('\\n'));";
  if (!generator.includes(writer) || !generator.includes("import 'dart:io';")) throw new Error("Unsupported mobile text generator; cannot install ARM compiler compatibility adjustment");
  await writeFile(helperPath, revised);
  await writeFile(path.join(/* turbopackIgnore: true */ root, "tool/studio_mobile_text_compiler.dart"), mobileTextCompilerTool);
  await writeFile(generatorPath, generator.replace("import 'dart:io';", "import 'dart:io';\n\nimport 'studio_mobile_text_compiler.dart';").replace(writer, ".writeAsStringSync(stabilizeMobileTextSource(lines.join('\\n')));"));
  return ["bounded-mobile-text-lookup"];
}
