import assert from "node:assert/strict";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { prepareFlutterCompatibility, splitMobileTextLookup } from "../../src/lib/flutter-compatibility";

test("large localization lookup preserves expressions, escaped labels and first-match semantics", () => {
  const source = String.raw`extension MobileText on BuildContext {
  String mobileText(String source, Map<String, Object> values) {
    final l10n = getLocalizations(this);
    return switch (source) {
      'Brand' => l10n.brand,
      'Escaped \' label' => l10n.value((values['name'] ?? '').toString(), values['count'] ?? 0),
      'Brand' => l10n.otherBrand,
      'Last' => l10n.last,
      _ => source,
    };
  }
}
`;
  const revised = splitMobileTextLookup(source, 3, 2);
  assert.ok(revised.includes("final l10n = getLocalizations(this);"));
  for (const expression of ["l10n.brand", "l10n.otherBrand", "l10n.last", "l10n.value((values['name'] ?? '').toString(), values['count'] ?? 0)"]) assert.ok(revised.includes(expression));
  const table = revised.slice(revised.indexOf("const _studioMobileTextBuckets"), revised.indexOf("@pragma"));
  assert.equal((table.match(/'Brand':/g) ?? []).length, 1);
  assert.match(table, /'Brand': 0/);
  assert.match(table, /'Last': 1/);
  assert.equal((revised.match(/@pragma\('vm:never-inline'\)/g) ?? []).length, 2);
  assert.equal(splitMobileTextLookup(revised), revised);
  assert.equal(splitMobileTextLookup(source), source);
});

test("Git-derived source includes a compatible generator and records only applied adjustments", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "studio-localization-test-"));
  try {
    assert.deepEqual(await prepareFlutterCompatibility(root), []);
    await mkdir(path.join(root, "lib/shared/helpers"), { recursive: true });
    await mkdir(path.join(root, "tool"));
    const helper = path.join(root, "lib/shared/helpers/mobile_text.dart");
    await writeFile(helper, `// Generated by tool/generate_mobile_text.dart\nextension MobileText on BuildContext {\n  String mobileText(String source, Map<String, Object> values) {\n    final l10n = getLocalizations(this);\n    return switch (source) {\n${Array.from({ length: 300 }, (_, index) => `      'Label ${index}' => l10n.label${index},`).join("\n")}\n      _ => source,\n    };\n  }\n}\n`);
    const generator = path.join(root, "tool/generate_mobile_text.dart");
    await writeFile(generator, "import 'dart:io';\nFile('helper.dart').writeAsStringSync(lines.join('\\n'));\n");
    assert.deepEqual(await prepareFlutterCompatibility(root), ["bounded-mobile-text-lookup"]);
    assert.match(await readFile(generator, "utf8"), /stabilizeMobileTextSource/);
    assert.match(await readFile(path.join(root, "tool/studio_mobile_text_compiler.dart"), "utf8"), /String stabilizeMobileTextSource/);
    assert.deepEqual(await prepareFlutterCompatibility(root), []);
    const revised = await readFile(helper, "utf8");
    for (let index = 0; index < 300; index++) assert.ok(revised.includes(`'Label ${index}' => l10n.label${index},`));
  } finally { await rm(root, { recursive: true, force: true }); }
});
